---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/integration.sh
  args: [
    --input-dir, git-repo
  ]
