---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  CF_MANIFEST_HOST:

inputs:
  - name: git-repo
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-integration

run:
  path: git-repo/ci/tasks/prepare-integration.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-integration,
    --version-file, version/number,
    --input-manifest, git-repo/manifest.yml,
    --artifactId, item-service,
    --packaging, jar
  ]
